Make cloud-bastion
Otus-DevOps-2020-08/ilya-golikov_infra pull request #2
Opened 2020-09-14 21:02 UTC by ilya-golikov

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Создана ветка cloud-bastion;
 - Создан аккаунт yandex-cloud;
 - Создан каталог infra;
 - Сгенерированы ключи ssh;
 - Созданы виртуальные машины bastion, sominternalhost;
 - На VM bastion установлен и настроен VPN pritunl;
 - Настроен сертификат Let's Encrypt для веб интерфейса Pritunl;

## Как проверить работоспособность:
 - Перейти по ссылке https://84.201.173.102.sslip.io/

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2020-09-15 06:35 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к ридми. ДЗ возвращаю на доработку.

2020-09-15 06:35 UTC, mrgreyves commented on README.md
> +`bastion_IP = 84.201.173.102`
Вот тут нужно убрать `

2020-09-15 07:29 UTC, ilya-golikov commented on README.md
> +`bastion_IP = 84.201.173.102`
Спасибо, исправил

2020-09-16 06:08 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-09-16 07:16 UTC, merged